### ISSUE TITLE
GTM code should be after opening body tag

### ISSUE THREAD

**Issue by gregreindel** [presidential-innovation-fellows/code-gov-web#11]
Hi! I believe the Google Tag Manager code should be placed immediately after the opening body tag - not before the closing body tag. https://developers.google.com/tag-manager/quickstart

**Comment by rossdakin** [comment]
Good call @gregreindel – thanks!

**Comment by gregreindel** [comment]
Side note: It is also that way on http://pif.gov - and in that case it could actually be causing issues because the GTM loads async and theres many scripts before it that do not.
