### ISSUE TITLE
Add Getting Started to README

### ISSUE THREAD

**Issue by IanLee1521** [presidential-innovation-fellows/code-gov-web#117]
For those of us that aren't as familiar with modern web development tools, would it be possible to add a short "Getting Started" section to the README to stand up a local instance of the site?

I *think* that it's `npm install`, but I'm new to Node.js as of today so I'm not sure that is right...

Thanks!

**Comment by anselmbradford** [comment]
Section exists at https://github.com/presidential-innovation-fellows/code-gov-web#getting-started, @IanLee1521 do you mean expand what's there?

Aside, CFPB has an open source project readme template at https://github.com/cfpb/open-source-project-template and would love feedback/usage.

**Comment by IanLee1521** [comment]
Well I just feel silly then... I would have sworn I'd looked at that whole file... I think the fact that it's buried down a bit threw me off.

I'll look at the template a bit and see if I have any recommendations. Thanks @anselmbradford
