### ISSUE TITLE
Deploy images in reasonable resolution

### ISSUE THREAD

**Issue by olov** [presidential-innovation-fellows/code-gov-web#131]
For example, src/assets/img/logos/press/fcw.jpg is 1021x483 pixels, 106K, but is shown as a small thumbnail on the front-page and shouldn't need to be larger than a few K. 106K is 17% of your initial page load total for me (Chrome, desktop). Other images in src/assets/img/logos/press/ seems to suffer from the same problem.

**Comment by lukad03** [comment]
@olov I must have missed the press images on deployment - the Agency images don't suffer from the same issue (same with the footer images).
