### ISSUE TITLE
Alternate instructions to mailto

### ISSUE THREAD

**Issue by rileytg** [presidential-innovation-fellows/code-gov-web#14]
Many users do not have the correct mail client open with mailtos (osx user's pop up Mail.app when they use gmail or yahoo, win users have outlook). 

When you try to manually email, you're prompted with (the `--` is first line of my signature): 

```
> --
Unknown command - "--". Try HELP.
```

Didn't take long to figure out I had to send `SUBSCRIBE CODE` but I suggest something like a `?` icon that when hovered or clicked shows instructions like: 
> "Send `SUBSCRIBE CODE` to LISTSERV@listserv.gsa.gov to join mailing list.

**Comment by neilmartis** [comment]
@rileytg @rossdakin @alfeld @konklone I think there should be textbox which should have a signup option so that the users directly inputs his email in the textbox rather than sending an email with button saying subscribe to mailing list.Like the way @18f does it for the newsletter and other postings

**Comment by konklone** [comment]
The list is for .gov and .mil email addresses only, right? It probably shouldn't even be on the homepage of code.gov if that's the case.

**Comment by gbinal** [comment]
Great point, @konklone.  Powers that be - is there a call on whether this is a public listserve?  

If not, let's take off the site.  

If so, +1 to making this better.

**Comment by rossdakin** [comment]
It's public. 

Working to make it friendlier. If anyone has a pointer to docs on POSTing a signup, please share.

**Comment by neilmartis** [comment]
@rossdakin I didn't understand the question

**Comment by mattbailey0** [comment]
Closing. Resolved by https://github.com/presidential-innovation-fellows/code-gov-web/commit/60ccd876e83bf54a2e22520aa9724a4baa8d111b
