### ISSUE TITLE
Bad footer link

### ISSUE THREAD

**Issue by michaelcpuckett** [presidential-innovation-fellows/code-gov-web#143]
When I just checked the footer link for GSA, it goes to `https://gsa.gov/` but that is a forbidden page. I think it should instead link to `https://www.gsa.gov` - or whoever hosts that website should be notified and advised to add a redirect or similar.

**Comment by bodnarbm** [comment]
This might have been fixed already since this issue was posted. `https://gsa.gov/` appears to resolve correctly.

```Bash
$ curl -I https://gsa.gov/
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Date: Sun, 06 Nov 2016 15:06:54 GMT
Location: /portal/category/100000
Transfer-Encoding: chunked
Connection: Keep-Alive
X-Frame-Options: SAMEORIGIN
```

Also worked when I clicked on the footer link directly in Chrome and Safari.

**Comment by michaelcpuckett** [comment]
Wow, weird. It's doesn't work over wifi on my MacBook or LTE on my iPhone. Are you perhaps using a government network? If not, could just be me...

```
$ curl -I https://gsa.gov/
HTTP/1.1 403 Forbidden
Date: Sun, 06 Nov 2016 15:16:23 GMT
Server: Apache/2.2.27.0 (Unix) vFabric/5.3.4 mod_ssl/2.2.27.0 OpenSSL/1.0.1g-fips DAV/2
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=iso-8859-1
```

**Comment by bodnarbm** [comment]
Weird. I was on my home network before when testing and it worked, but just tried on my iPhone off wifi and got the same 403.

So something somewhere is wrong.

**Comment by lukad03** [comment]
@michaelcpuckett It seems like this is an error on GSA's side, but that `www.gsa.gov` will resolve more consistently for folks. Can you verify that `www` works as expected?

**Comment by michaelcpuckett** [comment]
Yes, it works for me with www subdomain.

**Comment by uncompiled** [comment]
FWIW, https://gsa.gov works for me right now.

```
▶ httpstat -k https://gsa.gov

HTTP/2.0 302 Found
Server: Apache-Coyote/1.1
Content-Length: 0
Date: Mon, 07 Nov 2016 14:49:55 GMT
Location: /portal/category/100000
```

It looks like www.gsa.gov is CNAMEd to another record that has two A records attached to it.  That _might_ be more reliable.

**Comment by konklone** [comment]
GSA is still in-process of migrating to HTTPS, it's not a default or advertised feature yet. So I would revert the link to `http://www.gsa.gov` or `http://gsa.gov` for now.
