### ISSUE TITLE
How to format code.json?

### ISSUE THREAD

**Issue by CrazyPython** [presidential-innovation-fellows/code-gov-web#145]
[as specified here](https://code.gov/#/explore-code/repos/29924484)

**Comment by lukad03** [comment]
@CrazyPython Documentation for formatting a given Repo's `code.json` file can be found here: https://github.com/presidential-innovation-fellows/code-gov-web/blob/master/_draft_content/02_compliance/schema/code.json

**Comment by CrazyPython** [comment]
@lukad03 Should be posted in README and on website - the website complains about missing code.json.
