### ISSUE TITLE
Removed and renamed tslint rules cause 'npm test' failure

### ISSUE THREAD

**Issue by cdoremus** [presidential-innovation-fellows/code-gov-web#146]
A unit test run (npm test) fails due to two rules (label-undefined and use-strict) that have been removed from tslint and one rule that has been renamed (no-constructor-vars -> no-parameter-properties).

Here is the relevant documentation from the tslint project:
Remove label-undefined rule (#1614):
https://github.com/JoshuaKGoldberg/tslint/commit/bd9cbae732c9bfd841ba5fb1d12531ea15993b11
Remove use-strict rule (#1615):
https://github.com/JoshuaKGoldberg/tslint/commit/76e4e02ae99b6b41e1b9eeb12770992cc1fe17bc
Rename no-constructor-vars to no-parameter-properties (#1616):
https://github.com/palantir/tslint/pull/1616

Here is the error message and stack trace when the failure occurs:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: Module build failed: Error: 
       Could not find implementations for the following rules specified in the configuration:
       label-undefined
       use-strict
       no-constructor-vars
              Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
              If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
          
      at Object.loadRules (/home/craig/git/code-gov-web/node_modules/tslint/lib/ruleLoader.js:56:15)
      at MultiLinter.lint (/home/craig/git/code-gov-web/node_modules/tslint/lib/tslintMulti.js:101:44)
      at Linter.lint (/home/craig/git/code-gov-web/node_modules/tslint/lib/tslint.js:46:21)
      at Object.lint (/home/craig/git/code-gov-web/node_modules/tslint-loader/index.js:41:23)
      at Object.module.exports (/home/craig/git/code-gov-web/node_modules/tslint-loader/index.js:103:8)
  at config/spec-bundle.js:53126
```
I will submit a PR shortly to fix this issue.

**Comment by lukad03** [comment]
Closed by https://github.com/presidential-innovation-fellows/code-gov-web/issues/148 merge.
