### ISSUE TITLE
Links to gov't projects

### ISSUE THREAD

**Issue by wilsond** [presidential-innovation-fellows/code-gov-web#15]
My company has completed several federally funded projects using open source assets and I'd like to link to some of the public github repos that contain those projects.  I'd also like to include the narrative of the projects to explain what they do, etc.  Will this feature be available on your site?

Also do you need help building out features like this?  I could volunteer some team time if we have appropriate coding skills.  I have a great team certified in Drupal here in the US.  Thanks!

**Comment by mattbailey0** [comment]
We're currently researching the overall site design and strategy, so your question is timely!  Would you care to share the links here?

**Comment by mcmahonjohn** [comment]
@wilsond Could you share the links here?

**Comment by wilsond** [comment]
http://freeyourtest.com/
http://www.ncscpartners.org/Media/Default/PDFs/NCSC-Open-Source-Press-Release-6-9-15.pdf

**Comment by mattbailey0** [comment]
@wilsond thanks for your patience. For projects like these you will want to work through the Federal agencies that funded the work to ensure their inclusion. Happy to discuss further.
