### ISSUE TITLE
CircleCI tests not detecting breaking changes when required npm packages update

### ISSUE THREAD

**Issue by bodnarbm** [presidential-innovation-fellows/code-gov-web#152]
As noted by @cdoremus in #151, CircleCI is passing tests despite a required fix present in the unmerged #148. Without the fixes present in #148, tests ran after tslint was updated on 2016-11-03 should fail on fresh installations.

This seems to be caused by CircleCI caching the node_modules directory (for sake of speedy builds and test). Since the cached version of tslint satisfies the package.json requirements for tslint (4.0.0-dev.0), the node_modules cache is not broken and CircleCI rans with the old cache. However, newer installations of the repo will install tslint@4.0.0-dev.1, which change the breaking changes prompting #148. Because of the cache, CircleCI is not detecting this change.

I suggest modifying the CircleCI config to run `npm upgrade` so that CircleCI can both take advantage of the cache when npm packages have not change, but also to detect issues with newer installations that install update npm packages higher than the minimums specified in `package.json`

**Comment by lukad03** [comment]
@bodnarbm Thanks for picking this up. I've created a PR (https://github.com/presidential-innovation-fellows/code-gov-web/pull/156) prior to merging in https://github.com/presidential-innovation-fellows/code-gov-web/pull/151 and https://github.com/presidential-innovation-fellows/code-gov-web/pull/148 that updates npm before executing tests to verify that this is what's happening and you're correct. I'll merge in those other PRs and then merge in my most recent PR.

**Comment by lukad03** [comment]
Fixed by https://github.com/presidential-innovation-fellows/code-gov-web/pull/156
