### ISSUE TITLE
20% code release

### ISSUE THREAD

**Issue by neilmartis** [presidential-innovation-fellows/code-gov-web#16]
I can see this happening across agencies and Departments and feel very proud to contribute to source code as it builds trust,collaboration,team work,knowledge sharing across industry and its a good policy to have.It good to start with a small percentage and once we are able to gauge the impact we can always the increase the code release percentage.Win-Win for everyone.I am happy as this a huge step in the right direction not only for the United States but also as an example for the rest of the world to follow.

**Comment by rossdakin** [comment]
Thank you for you interest, @neilmartis!

We're also looking at other parts of the world (e.g. France, Estonia) to learn what we can from their similar efforts.
