### ISSUE TITLE
Harvest from federal Github repos?

### ISSUE THREAD

**Issue by DruidSmith** [presidential-innovation-fellows/code-gov-web#164]
Will Code.gov be set up to do an automated harvest from federal Github repos?   And if so, what would need to happen to make that work?

**Comment by mcmahonjohn** [comment]
This is related to #137 & #125. Specifically, 125#issuecomment-258345805

Basically, the plan in the long term is to harvest the listings for open projects, but for now they just wanted to highlight a few.

**Comment by lukad03** [comment]
@mcmahonjohn hit the nail on the head. Agencies are still working on getting the `code.json` files in order. We expect to have a lot more repos by the end of the year.
