### ISSUE TITLE
Discuss url link

### ISSUE THREAD

**Issue by neilmartis** [presidential-innovation-fellows/code-gov-web#17]
@afeld @rossdakin @konklone I am not sure if url is correct for the discussing the source policy as it takes you to the WhiteHouse/source-code-policy instead of presidential-innovation-fellows/code-gov-web
 is this correct.Can someone please check.The White House Source Code Policy discussion has already ended if I am correct just needed to clarify.Thank you

**Comment by rossdakin** [comment]
This is as intended.

Policy discussion (including the open comment period) has existed in that repo and should remain there for the time being.

This repo is exclusively for the website at this time.
