### ISSUE TITLE
Flesh out repo.component.spec.ts

### ISSUE THREAD

**Issue by cdoremus** [presidential-innovation-fellows/code-gov-web#175]
I'd like to complete the spec for RepoComponent inside of repo.component.spec.ts, which is stubbed out now. RepoComponent shows the lowest coverage according to the project's code coverage report.

There also appears to be an error in RepoComponent on line 39:
```
          this.repo.agency = this.agencyService.getAgency(this.repo.agency);
```
The argument to getAgency() should be *id*, the getRepo() argument .

**Comment by cdoremus** [comment]
I have started to work on this issue and discovered that the call to *this.agencyService.getAgency(this.repo.agancy)* on line 39 is, in fact, correct.

**Comment by lukad03** [comment]
@cdoremus I've updated the issue title to remove the reference to the RepoComponent error. Looking forward to seeing what you come up with!

**Comment by cdoremus** [comment]
@lukad03. I noticed a redundant null check on line 10 of repo.template.html. Still this and a couple of other checks for defined/not-null in the repo template file (lines 14 & 20) are not needed as only one check is necessary (*ngIf="repo.description" on line 10, for instance - see http://stackoverflow.com/a/5515349/3127468).  Can I remove these checks from repo.template.html? I will provide test cases for these modifications (both defined and not-null test cases) to make sure the refactoring doesn't break anything.

**Comment by lukad03** [comment]
@cdoremus There was some API weirdness early in development where `null` was being returned as `'null'` or `'null '`, resulting in this data displaying when it's not supposed to.

I took a quick look at `repos.json` and noticed that `null` doesn't appear to be an option for the `description` field anymore - however, I'm seeing `""` and `" "` as options for when it is blank.

If there's a generic way we can check for empty/null values here, that would certainly help. I'll sync up with the team and ask about what sanitation, if any, the API can do to ensure this field is more consistent in the future.

**Comment by cdoremus** [comment]
I added 14 tests that cover all the things I mentioned above (in addition to other test cases). I need to rebase my PR branch with recent changes to master and hope to submit something tomorrow for your review.

A generic way to do these checks/sanitation would be in a method in the RepoService that gets invoked in the template, but a utility class/service/directive/pipe might be better. Thinking about this for a moment, I would favor a pipe, which I can work on if you want.

**Comment by lukad03** [comment]
@cdoremus Having a pipe to handle this would be great. Looking forward to seeing the PR!

**Comment by cdoremus** [comment]
@lukad03, would the string 'undefined' be possible and be considered false ('falsy')? I am including the string 'null' (trimmed) as a false/falsy value.

**Comment by cdoremus** [comment]
I have put into PR #179 code for this issue including assuming that the trimmed strings 'null' and 'undefined' are undefined.

**Comment by lukad03** [comment]
Closed by https://github.com/presidential-innovation-fellows/code-gov-web/issues/179
