### ISSUE TITLE
Outline and MVP code.gov *ahead* of schedule

### ISSUE THREAD

**Issue by gbinal** [presidential-innovation-fellows/code-gov-web#19]
There's a number of significant requirements in the source code policy for agencies to implement by the 90 and 120 day mark (below).  

Though the policy does not require Code.gov until the 90 day mark, it has been rightly stood up immediately so that it can be built in the open, as an open source project.  Given the important work that agencies are facing in the 90 and 120 day timeframes, it definitely makes sense to outline a sense of what help code.gov is going to offer them as soon as possible and to try to deliver that help ahead of the 90 day mark as much as possible so that agencies can factor it into their work and benefit from it.  

Specifically, I'd suggest:
* creating an issue here to begin outlining what will go on code.gov
* standing up placeholder issues or files for those deliverables 
* beginning a conversation here about which deliverables are more urgently needed by agencies that may struggle with any of the 90/120 day requirements
* inviting the open source community to contribute to ^^^

The 90 and 120 day mark is going to come quickly for agencies and it's important that code.gov provide useful support early and often.  :)  

_Disclaimer: I'm really excited about Code.gov._  

-------------------

* _"Within 120 days of the publication date of this policy, each agency must update—and thereafter keep up to date—its inventory of agency information resources to include an enterprise code inventory that lists custom-developed code for or by the agency after the publication of this policy."_
* _"Within 90 days of the publication date of this policy, each agency’s CIO—in consultation with the agency’s CAO—shall develop an agency-wide policy that addresses the requirements of this document."_
* _"Moreover, within 90 days of the publication date of this policy, each agency’s CIO office must correct or amend any policies that are inconsistent with the requirements of this document, including the correction of policies that automatically treat OSS as noncommercial software."_

**Comment by mattbailey0** [comment]
Hi! Yep, we are on it. The core team is prepping essentially exactly what you're asking for here and will share as soon as possible. Look for updates here and on the mailing list, which folks can join via the current placeholder site.

**Comment by Stargator** [comment]
@mattbailey0 what this status of this issue then if the core team is working on it? Is this being kept because there are a couple of suggested items that could be added as issues ti be worked? If so, I would then recommend re-purposing this issue to specifically address them and place it under the appropriate milestone and label(s).

**Comment by mattbailey0** [comment]
@Stargator thanks for the nudge. This is issue cruft that should have been closed out several weeks ago.  As always, feel free to reopen if more discussion is needed or create new issues.
