### ISSUE TITLE
fix: end-to-end (e2e) tests fail

### ISSUE THREAD

**Issue by cdoremus** [presidential-innovation-fellows/code-gov-web#193]
Running the e2e tests using npm fails because the baseUrl port in protractor.conf.js is set to 3000, while the webpack configuration is port 2700 for dev and 8080 for prod and stage. I would like to set the baseUrl port to 2700, but I want to make sure the team is OK with this.

Also, instructions on how to run e2e tests need to be added to the Readme file.

**Comment by lukad03** [comment]
Let's change the port to `2700` in protractor.conf.js. I'm working on this and a few other projects, so keeping the port at `2700` will help me avoid port conflicts. It's a tad selfish, but currently I'm the only dev working on the front-end from our side :D
