### ISSUE TITLE
New background image

### ISSUE THREAD

**Issue by rossdakin** [presidential-innovation-fellows/code-gov-web#2]
Because PHP.

**Comment by LogoiLab** [comment]
I would say to choose something low-poly for the background.

**Comment by CrazyPython** [comment]
@konklone That has to fixed. It reflects the current state of the government's technology. We launch our nukes using floppy disks, the army was hacked by - of all methods - SQL Injection.

**Comment by neilmartis** [comment]
@CrazyPython @konklone @rossdakin I would like this image as a background if its okay.is it Jekyll based or PHP
![emoji_logo](https://cloud.githubusercontent.com/assets/10228512/17601204/f3b8dd90-5fd4-11e6-8dd4-deec85c30142.png)

**Comment by CrazyPython** [comment]
Also:

 - Supports IE 7
 - Link rel profile/pingback? Invalid relationship. The link also goes to this site: http://gmpg.org/xfn/11
 - PHP in the inside of the body tag. Like as an attribute.
 - Not sure if it's valid PHP
 - The title is PHP code. Seriously??
 - Charset as PHP code.

**Comment by CrazyPython** [comment]
And on this repository:

 - duplicated images (should use symlink)
 - you're making this site open source but not healthcare.gov. Opening this up has no practical benefit, opening up healthcare.gov means an accelerated peer review process and less hackers getting in
 - please make all CIA confidential stuff in a GitHub repository please. I want to submit a pull request. The diff looks like this:
```filename: .env
+ export DID_BUSH_DO_9/11=true
```

**Comment by afeld** [comment]
Hi folks- Let's keep this issue focused on deciding on a new background image. Thanks!

**Comment by CrazyPython** [comment]
It must have easter eggs.

**Comment by RobertRM** [comment]
Ha, somewhat ironically, it's code from Wordpress.

**Comment by LogoiLab** [comment]
So we basically ripped off a default wordpress  background...did we like use Google for all our images...we can't do that its not legal in most cases..."open source" government...stealing proprietary images.

**Comment by derekeder** [comment]
May I suggest that you use the source code from https://sourcecode.cio.gov/

Seems to have well-formed HTML, uses HTTPS, and is highly relevant.

**Comment by CrazyPython** [comment]
@derekeder The code is good, but the colors? I suggest opening it in IntelliJ WebStorm, Darcula theme. It also seems to be the colorscheme used in the original photo.

Even better, a camera angle like the previous one and/or an animation of typing.

**Comment by LogoiLab** [comment]
May I suggest you change some of the file names for files stored on non-cdn servers.

**Comment by derekeder** [comment]
@CrazyPython right. to maintain continuity with the current image, apply the same color scheme and effects to the new source code.

**Comment by CrazyPython** [comment]
@derekeder and the current image's colors are pretty ugly

**Comment by CrazyPython** [comment]
Hm, WebStorm doesn't seem to have a good theme. Anybody know what editor was used in the photo?

**Comment by LogoiLab** [comment]
You could whip a theme up real quick for atom

**Comment by CrazyPython** [comment]
@LogoiLab eh, requires color sampling. could do the same with WebStorm

**Comment by styfle** [comment]
Using the suggestion from @derekeder I made this:

![img](http://i.imgur.com/SeXcZC7.png)

http://i.imgur.com/SeXcZC7.png

![blur](http://i.imgur.com/Yf09HIQ.jpg)

http://i.imgur.com/Yf09HIQ.jpg

**Comment by CrazyPython** [comment]
@styfle good effects, bad colors though. It could be done with CSS.

**Comment by okamanda** [comment]
Thanks all. We've updated the background image, which now features code from code.gov

**Comment by CrazyPython** [comment]
@okamanda pretty low d. and it'd be nice if you could show some actual code and not just HTML.

**Comment by CrazyPython** [comment]
and /src/img should be updated as well. should be a symlink.

**Comment by konklone** [comment]
I think the new image is good :)

**Comment by derekeder** [comment]
Looks good!

**Comment by rossdakin** [comment]
@CrazyPython — thanks for keeping an eye on redundancy!

The reason we have two is that the version in `src` is the high-res original, whereas the version in `dist` is compressed for efficiency.

**Comment by CrazyPython** [comment]
@rossdakin darn our budget is lo

**Comment by rossdakin** [comment]
@CrazyPython we love GH Pages. Unfortunately, they don't yet support encryption on custom domains.

https://github.com/isaacs/github/issues/156

https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by CrazyPython** [comment]
@rossdakin What if you `src`ed to the `raw.githubusercontent/...` pages? Or if you renamed the master branch to gh-pages and `src`ed to the image? More dynamic, more HD, and less tax dollars wasted.

Lemme repeat that.

Less tax dollars wasted.

Less tax dollars wasted.

🇺🇸 💵

**Comment by neilmartis** [comment]
@CrazyPython

**Comment by neilmartis** [comment]
@CrazyPython :muscle::computer::us:

**Comment by rossdakin** [comment]
@CrazyPython to be clear, having two versions of this image doesn't cost anything.

**Comment by CrazyPython** [comment]
@rossdakin well you have a compressed version of the image for a reason - to save bandwidth and money.
