### ISSUE TITLE
Plans to add NSF as an Agency?

### ISSUE THREAD

**Issue by pjmaechling** [presidential-innovation-fellows/code-gov-web#203]
National Science Foundation (NSF) projects produce a lot of useful software. Can you include NSF as an agency distributing codes through code.gov?

**Comment by mattbailey0** [comment]
Good question! 

Short answer: yes, NSF can opt to be included.

Longer answer: As an independent agency, NSF is not required to comply with the [Federal Source Code Policy](https://sourcecode.cio.gov), which is what requires [CFO Act](https://cfo.gov/about/) agencies to inventory their code and participate in the open source program.  That being said, NSF does incredible work, and we'd love to include it!
