### ISSUE TITLE
Schema difference between code.gov spec and sample code.json file

### ISSUE THREAD

**Issue by ckaran** [presidential-innovation-fellows/code-gov-web#209]
The `code.json` spec at https://code.gov/#/policy-guide/docs/compliance/inventory-code requires the use of the `project` key, but the sample [code.json](https://github.com/presidential-innovation-fellows/code-gov-web/blob/master/_draft_content/02_compliance/schema/code.json) file is using the `projects` key.  Can you please update one or the other to whatever is the latest requirement?

**Comment by IanLee1521** [comment]
@ckaran -- You might want to check out #200 which updated the schema in the GitHub repo: https://github.com/presidential-innovation-fellows/code-gov-web/blob/master/_draft_content/02_compliance/05-metadata-schema-definition.md

That said, you're correct in that the content at code.gov still needs to get updated / regenerated (see: https://github.com/presidential-innovation-fellows/code-gov-web/pull/200#issuecomment-266523343)

**Comment by ckaran** [comment]
Will do.  In that case, I'll continue my comments on #200
