### ISSUE TITLE
add a code of conduct

### ISSUE THREAD

**Issue by mattbailey0** [presidential-innovation-fellows/code-gov-web#22]
Add a code of conduct for this repository.  [18F has a good one](https://github.com/18F/code-of-conduct) that may be appropriate to adopt more or less directly but will need a quick read through.

**Comment by Diamons** [comment]
Disagree. There's several issues with the 18F code of conduct. For starters:

`If you are unsure if something is appropriate behavior, it probably isn’t. Each person you interact with can define where that line is for them. `

If this is an American government project, one of the most important considerations is the First Amendment. Regardless of whether or not you like a certain comment or found it inappropriate, the right to say that is more important than an individual's feelings.

I could go on and on. There's just no room for that here in the grand scheme of things. Friction is normal and healthy.
