### ISSUE TITLE
Errors with optional fields prevents agency code from publishing on code.gov

### ISSUE THREAD

**Issue by trycrmr** [presidential-innovation-fellows/code-gov-web#229]
I am helping the State Department populate their code.json. The [code.gov api](https://code-api.app.cloud.gov/api/0.1/status/DOS/issues) has been really helpful for linting! 

We are on our third iteration of the code.json. The last two times we had errors with optional fields. In the key-value pair for the optional field I had set the value to null. In both cases the issues this caused were preventing our agency's repositories from appearing on code.gov.

My question is why errors with optional fields are allowed to inhibit the code.json from being published? Is there another way errors with optional fields could be handled so they don't withhold an agency's code.json discoverability when every required field has been appropriately populated?

From the outside looking in it feels like a bureaucratic hurtle that can be removed. Looking forward to the dialogue on this behavior! 

![image](https://cloud.githubusercontent.com/assets/6002123/24325432/399f14cc-116f-11e7-9e55-b64f1772704a.png)

**Comment by okamanda** [comment]
@trycrmr We've updated the compliance dashboard with new logic, per your comment. DOS is no longer showing errors.

**Comment by trycrmr** [comment]
I see our project appearing on code.gov! Thanks @okamanda !
