### ISSUE TITLE
Cross-browser compatibility

### ISSUE THREAD

**Issue by AlvandSalehi** [presidential-innovation-fellows/code-gov-web#236]
Issues with how Code.gov appears on Internet Explorer (v11):

Homepage
- Font type, font size, and line spacing are inconsistent with Chrome
- Press section: Quotations icon and Wired logo are not rendering properly

Explore Code
- None of the assets are showing up in project previews and project pages (e.g., assets for language, open source, license, activity)

**Comment by okamanda** [comment]
@AlvandSalehi Are you still seeing this problem?

**Comment by AlvandSalehi** [comment]
Looks like it's fixed. Nice work!

**Comment by okamanda** [comment]
Great.
