### ISSUE TITLE
Are policy guide and sample_code.json up to date?

### ISSUE THREAD

**Issue by iadgovuser1** [presidential-innovation-fellows/code-gov-web#239]
Looking at https://github.com/presidential-innovation-fellows/code-gov-api/tree/master/schemas/repo it seems like agency isn't supposed to be directly assigned a string as shown in /src/assets/sample_code.json and discussed at https://code.gov/#/policy-guide/docs/compliance/inventory-code 

It looks like there are supposed to be properties (name, acronym, etc)) below agency.

It also doesn't look like it is required as discussed in the policy guide.

**Comment by iadgovuser1** [comment]
For example:

Docs show: 
- agency: "blah"

Schema code looks like: 
- agency: { name: "blah", acronym: "blah", website: "blah", codeUrl: "blah" }

**Comment by okamanda** [comment]
Thanks @iadgovuser1 

The policy guide is up to date, but what you're seeing is that our API creates an agency object based on data that it's gathering from other sources. The creation of the agency object is an interim step we're taking on the backend before rendering the final version you see in production.

**Comment by iadgovuser1** [comment]
@okamanda Thanks. I just updated our code.gov json to reflect the correct structure.
