### ISSUE TITLE
Software catalog - metadata standard:  JSON-LD  (schema.org)

### ISSUE THREAD

**Issue by rafael5** [presidential-innovation-fellows/code-gov-web#24]
The world's largest search engines (Google, Yahoo, Microsoft, Yandex) have collaborated on creating a Linked Data (semantic web) based schema such that all search engines can index and structure all data on the web using a single common schema. 

This is at https://schema.org

Recommendation:  adopt the W3C Linked Data standard (JSON-LD) for the code.gov software catalog using the  Google/Microsoft/Yahoo  schema.org metadata model for Software Application:

https://schema.org/SoftwareApplication

Note that the U.S. Department of Veterans Affairs, U.S. National Library of Congress, and many other federal agencies and knowledge organizations have already adopted the W3C Linked Data standard and JSON-LD  as their metadata standard, making them fully W3C compliant for web search engines.

**Comment by okamanda** [comment]
version 1.0.1 schema has been released [which incorporates various standards as applicable](https://code.gov/#/policy-guide/docs/compliance/inventory-code). There will be opportunities to shape future version of the schema.
