### ISSUE TITLE
Required content: -	Advice on how agencies can strengthen internal capacity to efficiently and securely deliver OSS as part of regular operations (7.1)

### ISSUE THREAD

**Issue by mattbailey0** [presidential-innovation-fellows/code-gov-web#26]
[Section 7.1 of the policy](https://sourcecode.cio.gov/Implementation/) states that: 

>  in support of the objectives and requirements of this policy, agencies should strengthen internal capacity to efficiently and securely deliver OSS as part of regular operations. Additional information on this topic will be provided on Code.gov

**Comment by jbjonesjr** [comment]
One way for agencies to be better prepared for delivering open source is to live by those same processes internally. [Inner Sourcing](paypal.github.io/InnerSourceCommons/) (quickly becoming a buzzword these days... sigh) is the idea of using open sourcing principles (sharing code outside of your immediate team, encouraged reuse of others work, colocation not required, very public/complete written communication and documentation, and tests as a way to convey purpose in the absence of original author) inside an organization or agency.

By getting teams comfortable with dealing with those patterns and philosophies on internal work, this will make the transition to open source work easier.

This also dovetails into the Government Reuse portions of the policy as well....

_Something something multiple birds something something single stones...._
