### ISSUE TITLE
BIDS State Department Repo - Project

### ISSUE THREAD

**Issue by neilmartis** [presidential-innovation-fellows/code-gov-web#263]
Hi All 

I don't know if this is a right place to ask the question. The BIDS Project of State Department is listed on Code.gov but its neither Open Source or Proprietary how do we work on the repo or contribute to it . Also not many projects are Open Source  https://code.gov/#/explore-code/repos/dos_department_state_information_resource_management_s_office_of_ediplomacy_bids

Thanks,
Neil

**Comment by okamanda** [comment]
Hi @neilmartis 
Thanks for your note. The BIDS project is listed as [Government-Wide Reuse](https://code.gov/#/explore-code/agencies/DOS), meaning that the source code is only available for sharing among federal employees/agencies. You'll notice that if you click on the 'Contact Agency' button, you'll get an email address for a point-of-contact at the agency. That person should have more information about the repo and how to contribute to it.

**Comment by neilmartis** [comment]
@okamanda Thank you so much Oliver for answering the question. I will surely contact the agency.
