### ISSUE TITLE
Required content: Advice on existing code repositories and common third-party repository platforms that agencies can use to satisfy the requirements of this policy (7.4)

### ISSUE THREAD

**Issue by mattbailey0** [presidential-innovation-fellows/code-gov-web#27]
[Section 7.4 of the policy](https://sourcecode.cio.gov/Implementation/) states that:

> Accessible, buildable, version-controlled repositories for the storage, discussion, and modification of custom-developed code are critical to both the Government-wide reuse and OSS pilot program sections of this policy. Agencies should utilize existing code repositories and common third-party repository platforms as necessary in order to satisfy the requirements of this policy.36 Code.gov will contain additional information on this topic.

**Comment by jbjonesjr** [comment]
As exhibited in https://github.com/presidential-innovation-fellows/code-gov-web/issues/31 , there is already a large Government presence on GitHub.com, a common source of open source software and project hosting, to the tune of [38 million repositories and 15 million users](https://github.com/about.htm) (and the host of awesome projects like `code.gov`).

There are many other options for code hosting out there, but none combine the technology, innovation, and community that GitHub does.

For those organizations that have restrictions on what data or code they can store in the "the cloud", [GitHub Enterprise](https://enterprise.github.com) provides them the same features and tooling of GitHub.com, but hosted in their own data centers or private clouds.

Between GitHub.com and GitHub Enterprise, options are available for customers to meet both the open source and federal reuse directives of this policy from GitHub.

--- 

_Disclaimer: I work for GitHub, and help the Govt make better software with it._
