### ISSUE TITLE
Required content: Metadata schema to help agencies fill out enterprise code inventory (7.2)

### ISSUE THREAD

**Issue by mattbailey0** [presidential-innovation-fellows/code-gov-web#30]
[Section 7.2 of the policy](https://sourcecode.cio.gov/Implementation/) states that:
> Within 120 days of the publication date of this policy, each agency must update—and thereafter keep up to date—its inventory of agency information resources to include an enterprise code inventory that lists custom-developed code for or by the agency after the publication of this policy. [..] Agencies shall fill out this information based on a metadata schema that OMB will provide on Code.gov.

**Comment by rafael5** [comment]
The U.S. Department of Veterans Affairs, U.S. National Library of Congress, U.S. National Library of Medicine, and many other federal agencies and knowledge organizations have  adopted the W3C Linked Data standard  (Resource Description Framework / RDF)  as their metadata standard, making them fully W3C compliant for web search engines.   

The world's largest search engines (Google, Yahoo, Microsoft, Yandex) have collaborated on creating a RDF schema such that all search engines can index and structure all data on the web using a single common schema.  

This is at https://schema.org

Recommendation:  adopt the W3C Linked Data standard (RDF) and the Google/Microsoft/Yahoo  schema.org  RDF model for Software Application to maximize search and discoverability of software published on the web:

https://schema.org/SoftwareApplication

Note: To make this easy for adopters, not all of the schema.org  SoftwareApplication fields need to be used.  However, if this schema.org model is used (or any part of it) it means that all the software will be discoverable through all standard search engine technology.

**Comment by mattbailey0** [comment]
See discussion on this issue here: https://github.com/WhiteHouse/source-code-policy/issues/117

**Comment by mattbailey0** [comment]
In addition to the schema definition itself, it's important that agencies have easy to understand instructions on how to work with it in building their code inventory.  [We've created a draft here.](https://github.com/presidential-innovation-fellows/code-gov-web/issues/30).

- Is it clear and comprehensive?
- Can it be better organized?
- What additional questions are agencies likely to have?

**Comment by mattbailey0** [comment]
Consolidating related discussions at #41
