### ISSUE TITLE
Canonical list of agencies covered by policy, existing public repos

### ISSUE THREAD

**Issue by mattbailey0** [presidential-innovation-fellows/code-gov-web#31]
@okamanda says:

> I'm trying to create a table of where executive agencies are hosting repos (e.g., github, bitbucket, etc), and I'm going by the list defined by [Clinger-Cohen](https://en.wikipedia.org/wiki/Clinger%E2%80%93Cohen_Act).  I have the following, but I know I'm missing some. Do we have a current list?:

Agency Name ACRONYM
Department of Agriculture   USDA
Department of Commerce  DOC
Department of Defense   DOD
Department of Education ED
Department of Energy    DOE
Department of Health and Human Services HHS
Department of Housing and Urban Development HUD
Department of Interior  DOI
Department of Justice   DOJ
Department of Labor DOL
Department of State DOS
Department of Transportation    DOT
Department of Treasury  TRE
Department of Veterans Affairs  VA
Environmental Protection Agency EPA
National Aeronautics and Space Administration   NASA
Agency for International Development    AID
Federal Emergency Management Agency FEMA
General Services Administration GSA
National Science Foundation NSF
Nuclear Regulatory Commission   NRC
Office of Personnel Management  OPM
Small Business Administration   SBA

```
```

**Comment by rafael5** [comment]
Here is another list of government Github repositories:

https://govtgit.com/

Centers for Disease Control and Prevention (CDC)
Centers for Medicare and Medicaid Services (CMS)
Consumer Financial Protection Bureau
Department of Agriculture (USDA)
Department of Commerce
Department of Defense (DOD)
Department of Education (ED)
Department of Energy (DOE)
Department of Health and Human Services (HHS)
Department of Homeland Security (DHS)
Department of Labor (DOL)
Department of State
Department of Veterans Affairs (VA)
Department of the Air Force
Department of the Army
Department of the Interior (DOI)
Department of the Interior (DOI)
Economic Research Service (ERS)
Environmental Protection Agency (EPA)
Executive Office of the President (EOP)
Federal Communications Commission (FCC)
Federal Reserve System
Food and Drug Administration (FDA)
General Services Administration (GSA)
Institute of Museum and Library Services (IMLS)
International Trade Administration
Library of Congress (LOC)
Millennium Challenge Corporation (MCC)
National Aeronautics and Space Administration (NASA)
National Archives and Records Administration (NARA)
National Geospatial-Intelligence Agency (NGA)
National Guard Bureau
National Institute of Standards and Technology (NIST)
National Institutes of Health (NIH)
National Mediation Board (NMB)
National Oceanic and Atmospheric Administration (NOAA)
National Park Service (NPS)
Office of Personnel Management (OPM)
Office of the Director of National Intelligence (DNI)
Peace Corps
Smithsonian Institute
United States Agency for International Development (USAID)
United States Geological Survey (USGS)

**Comment by okamanda** [comment]
thanks @rafael5

**Comment by okamanda** [comment]
Here's a starting table for tracking some of these repos:

[Code.gov Agency Inventory Survey.xlsx](https://github.com/presidential-innovation-fellows/code-gov-web/files/448348/Code.gov.Agency.Inventory.Survey.xlsx)

**Comment by okamanda** [comment]
Updated:
[Code.gov Agency Inventory Survey.xlsx](https://github.com/presidential-innovation-fellows/code-gov-web/files/457362/Code.gov.Agency.Inventory.Survey.xlsx)

**Comment by jbjonesjr** [comment]
Additional Government Orgs on GitHub: https://government.github.com/community/
