### ISSUE TITLE
Backlog of needed content for implementers

### ISSUE THREAD

**Issue by mattbailey0** [presidential-innovation-fellows/code-gov-web#32]
We need to build a backlog of content that will be helpful for folks at agencies who are implementing the [sourcecode policy](https://sourcecode.cio.gov/Implementation/).  There are number of explicitly required topics, which I've already opened issues for individually and marked as "Required Content:"

However, there are likely a number of other topics that agencies could use more elaboration on.  We need to build a backlog of that content to start writing.  We'll do that in part through user research but can use input here as well.

**Comment by mattbailey0** [comment]
TODO: https://github.com/WhiteHouse/source-code-policy/issues/251

**Comment by Stargator** [comment]
@mattbailey0 I would suggest creating a label called "Required Content" so it is easier to sort for. You may even want to add a link to it in the README.

**Comment by mattbailey0** [comment]
@Stargator done.

**Comment by mattbailey0** [comment]
Closing this based on the evolving outline available here https://github.com/presidential-innovation-fellows/code-gov-web/blob/master/_draft_content/README.md
