### ISSUE TITLE
Code.gov source code catalog/ model:   Schema.org/SoftwareSourceCode

### ISSUE THREAD

**Issue by rafael5** [presidential-innovation-fellows/code-gov-web#37]
### Recommendation:  Schema.org  for source code metadata model

 **Schema.org**  The Schema.org is the web data model used by the largest web search engines (Google, Yahoo, Microsoft Bing, etc.)  to index and search all structured data on the web. Using schema.org  will thus maximize the discoverability of all software artifacts published on the web.  See:  https://schema.org
### Specifically for code.gov source code
- https://schema.org/SoftwareSourceCode
### Background

Federal agencies and knowledge organizations such as IBM,  Google (Knowledge Graphs)  and  National Library of Congress have  adopted the W3C Linked Data standard (RDF) as their metadata standard to provide master data management for all their large data resources,  making them compliant with all web search engines and technologies.   VA, for example,  is projecting all of its data assets using Schema.org  JSON-LD to surface all 35 years of its data:

http://vistadataproject.info

**JSON-LD**. This is the W3C Linked Data standard for structured data on the web,  also known as the Resource Description Framework (RDF). The JSON-LD serialization of RDF is the most web-programmer friendly form of RDF, and supplements the JSON standard with the "@ context" attribute. See:  
- http://json-ld.org/
- https://developers.google.com/schemas/formats/json-ld

**Comment by mattbailey0** [comment]
Closing this as duplicative of #24
