### ISSUE TITLE
What if we want to showcase our repos but it's currently against the policy of our organization?

### ISSUE THREAD

**Issue by mikecharles** [presidential-innovation-fellows/code-gov-web#45]
I work for the Climate Prediction Center (DOC/NOAA/NWS/NCEP), and I have a few open source repos that I'd love to showcase in the initial code.gov launch. However, as per [NOAA's IT Security Awareness Course](http://noaa.learnsecuritywith.us/) it's currently against NOAA's IT policy to use a non-accredited cloud service (specifically calling out GitHub.com), making it impossible to showcase our work (and impossible to comply with the FSCP). To quote the course:

> NOAA-Accredited Services are those for which the NOAA Acquisition and Grants Office has issued a contract award and a NOAA Senior Manager, such as the NOAA CIO, has reviewed the cloud service's security posture and made a risk-based decision to allow the use of the services "as is" or with mitigation from an independent assessor's findings.
> 
> Non-accredited cloud services have not been issued a NOAA contract award and/or a NOAA Senior Manager has not reviewed the service's security posture and made a risk-based decision to allow the use of the cloud services.
> 
> Non-accredited (less secure) cloud services include but are not limited to: iCloud, Dropbox, Box.net, Evernote, github, Constant Contact, and Springpad.
> 
> You may not store government data in non-accredited cloud services.

 Questions:

1. How can I still showcase some open source repos? A URL to a tarball would kill my soul a little...
2. How do we push management to reverse such policies in a timely fashion so we can start complying with the FSCP?

**Comment by IanLee1521** [comment]
Also, as the policies on publicizing internal code are growing in parallel, is their guidance on how to showcase new internal codes, in addition to things that may already be open sourced?

**Comment by mattbailey0** [comment]
Hi @mikecharles - good questions.  First off, NOAA/Commerce is indeed covered by the policy.  The most important thing is to work with your agency to ensure that you stay in-bounds and in order to effect longer term positive change. 

I'd love to help.  Maybe the easiest thing is to email code@listserv.gsa.gov from your work email, which will be routed to me.  Let's chat.

**Comment by mikecharles** [comment]
> I'd love to help. Maybe the easiest thing is to email code@listserv.gsa.gov from your work email, which will be routed to me. Let's chat.

Done, thanks!

**Comment by bandrzej** [comment]
@mikecharles @mattbailey0 
There will be tons of "ditto" to this.  

In my personal opinion, not that of my agency:

1. GitHub.com for Government use operates only under a [GSA DigitalGov Terms of Service agreement](https://help.github.com/articles/amendment-to-github-terms-of-service-applicable-to-government-users), not a FedRAMP Authorization nor FedRAMP ATO.  *Many* agencies require the ATOs to post government information. 

1. While this is great for public-facing, open-source code from agencies, there will be significant issues to overcome for Government-wide reuse part of the policy not intended for public-release, which these projects and its code are typically CUI/FOUO by their very existance.

**Comment by IanLee1521** [comment]
@mikecharles -- I was just looking at https://github.com/presidential-innovation-fellows/code-gov-web/issues/43#issue-177822073 and based on the link to 18F's [setting up GitHub](https://pages.18f.gov/open-source-program/setting-up-github/) guide (under "Important Links":

> ”…to clarify, all government staff and contractors (along with the public) should be able to create GitHub accounts and engage with this project by filing issues, comments, and pull requests. If restrictions exist at your agency that conflict with this, you should reach out to the Office of the Federal CIO at ofcio@omb.eop.gov to discuss this matter further.” - [OMB Office of the Federal CIO statement on GitHub use](https://github.com/project-open-data/project-open-data.github.io/issues/346#issuecomment-169140589)

That's dealing specifically with accounts, but organizations / general GitHub use might be something worth directing their way as well...

**Comment by mikecharles** [comment]
Thanks @IanLee1521
