### ISSUE TITLE
SPDX - Opensource Software Package Exchange

### ISSUE THREAD

**Issue by mrtoddalexander** [presidential-innovation-fellows/code-gov-web#62]
Can an SPDX file or reference identifier for the tracking of opensource software package licenses be included? Including the SPDX standard for tracking opensource packages that may be used within code repositories could provide for streamlined 3rd party license auditing or analysis.

## About SPDX

The Software Package Data Exchange® (SPDX®) specification is a standard format for communicating the components, licenses and copyrights associated with software packages.

The SPDX standard helps facilitate compliance with free and open source software licenses by standardizing the way license information is shared across the software supply chain. SPDX reduces redundant work by providing a common format for companies and communities to share important data about software licenses and copyrights, thereby streamlining and improving compliance.

The SPDX specification is developed by the SPDX workgroup, which is hosted by the Linux Foundation. The grass-roots effort includes representatives from more than 20 organizations—software, systems and tool vendors, foundations  and systems integrators—all committed to creating a standard for software package data exchange formats.

https://spdx.org/learn

**Comment by jbjonesjr** [comment]
@mrtoddalexander this is very interesting! Making it easier to understand the dependencies, licenses, and heritage of projects is clearly a valuable stage in the software security process.

I would say that in my tours of Govt software development, I have not seen SPDX used by any projects (yet!). I think it would be premature to require this to be used, as it would be a far departure from the process these projects are using. However, I agree that code.gov should definitely suggest it as a software `best-practice`.

**Comment by mrtoddalexander** [comment]
Thanks @jbjonesjr. Yes, I agree. It is a far departure and should be recommended as a best-practice at this point. It would be great if any guidance for standardization of open-source license tagging would be suggested. An SPDX standard adoption could drive private and public FOSS (Federal Open Source Software) standard harmonization. 

And would be even better if SPDX standards supported the applicable Code.gov discovery standard in their schema.  I'm not only thinking about auditing. I am also thinking about the impact in govTech innovation this may drive.

**Comment by mattbailey0** [comment]
Thanks for this @mrtoddalexander - really interesting.  We'll keep an eye on this as we build out advice to agencies on open development and use of/contribution to non-gov code.  💯
